# Generated by Django 5.1.3 on 2024-12-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_useraddress_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
